on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:

  build:
    name: build 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        # Build for these versions to force backward compat with certain
        # toolchains (GLIBC < 2.29 in case of ubuntu-18.04)
        - ubuntu-18.04
        - macos-10.15
        py:
        - 3.7
        - 3.8
        - 3.9
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - id: tag
      uses: dawidd6/action-get-tag@v1
    - run: cargo +nightly build --release
    - working-directory: target/release
      run: tar -czf synth.tar.gz synth
    - uses: actions/upload-artifact@v2
      with:
        name: synth-${{ steps.tag.outputs.tag }}-${{ matrix.os }}-py${{ matrix.py }}-x86_64
        path: target/release/synth.tar.gz

  release:
    name: release
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag }}
        release_name: ${{ steps.tag.outputs.tag }}
        draft: true
        prerelease: false
    - run: echo '${{ steps.create_release.outputs.upload_url }}' > upload_url
    - uses: actions/upload-artifact@v2
      with:
        name: upload_url
        path: ./upload_url

  upload-nix-installer:
    name: upload-nix-installer
    needs: [ release ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: upload_url
        path: ./
    - id: release
      run: echo "##[set-output name=upload_url;]$(cat upload_url)"
    - working-directory: tools/nix
      run: |
        cp install.nix default.nix
        sed -i \
            -e "s|master|$GITHUB_REF|g" \
            -e "s|HEAD|$GITHUB_SHA|g" \
            default.nix
        tar -cvf install-nix default.nix
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }} 
        asset_path: ./tools/nix/install-nix
        asset_name: install-nix
        asset_content_type: application/octet-stream

  upload:
    name: upload
    needs: [ release ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - ubuntu-18.04
        - macos-10.15
        py:
        - 3.7
        - 3.8
        - 3.9
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: upload_url
        path: ./
    - id: release
      run: echo "##[set-output name=upload_url;]$(cat upload_url)"
    - id: tag
      uses: dawidd6/action-get-tag@v1
    - uses: actions/download-artifact@v2
      with:
        name: synth-${{ steps.tag.outputs.tag }}-${{ matrix.os }}-py${{ matrix.py }}-x86_64
        path: ./
    - run: ls
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }} 
        asset_path: ./synth.tar.gz
        asset_name: synth-${{ matrix.os }}-py${{ matrix.py }}-x86_64
        asset_content_type: application/octet-stream
